language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: test
      script: "mvn -Dtest=com.example.webfluxdemo.component.** test"
    - stage: build
      script: "mvn clean install -DskipTests=true"